numero = input("Entra com o número: ")
numero = int(numero)
# print("Olá " * 9)

print("1 * " + str(numero) + " = " + str(1 * numero))
print("2 * " + str(numero) + " = " + str(2 * numero))
print("3 * " + str(numero) + " = " + str(3 * numero))
print("4 * " + str(numero) + " = " + str(4 * numero))
print("5 * " + str(numero) + " = " + str(5 * numero))
print("6 * " + str(numero) + " = " + str(6 * numero))
print("7 * " + str(numero) + " = " + str(7 * numero))
print("8 * " + str(numero) + " = " + str(8 * numero))
print("9 * " + str(numero) + " = " + str(9 * numero))
print("10 * " + str(numero) + " = " + str(10 * numero))